// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJCPFAadIGveHWF-IYGgq_B6wA9imigk',
    appId: '1:908007748621:web:9a4e883f0fab3991b4d144',
    messagingSenderId: '908007748621',
    projectId: 'moviesapp-1396b',
    authDomain: 'moviesapp-1396b.firebaseapp.com',
    storageBucket: 'moviesapp-1396b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHCY1mbbuEHIM-Zn8WbPK42S0-YBbixg8',
    appId: '1:908007748621:android:54f777f1c33d91a9b4d144',
    messagingSenderId: '908007748621',
    projectId: 'moviesapp-1396b',
    storageBucket: 'moviesapp-1396b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_YTXrlJVMoEWwRq5dE7yEiUIVMYFeAQ',
    appId: '1:908007748621:ios:1987a81eab742abdb4d144',
    messagingSenderId: '908007748621',
    projectId: 'moviesapp-1396b',
    storageBucket: 'moviesapp-1396b.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_YTXrlJVMoEWwRq5dE7yEiUIVMYFeAQ',
    appId: '1:908007748621:ios:1987a81eab742abdb4d144',
    messagingSenderId: '908007748621',
    projectId: 'moviesapp-1396b',
    storageBucket: 'moviesapp-1396b.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJCPFAadIGveHWF-IYGgq_B6wA9imigk',
    appId: '1:908007748621:web:ba6e0d4d8070cd41b4d144',
    messagingSenderId: '908007748621',
    projectId: 'moviesapp-1396b',
    authDomain: 'moviesapp-1396b.firebaseapp.com',
    storageBucket: 'moviesapp-1396b.firebasestorage.app',
  );
}
